### ISSUE TITLE
Get new access token with client id and client secret only

### ISSUE THREAD

**Issue by feedm3** [thelinmichael/spotify-web-api-node#112]
Hi guys,
on the spotify api guide there is the "[Client Credentials Flow](https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow)" for authorizing with the client id and client secret only. Is there a way to do this with the web api node?
Why: I'm using the spotify api server side so I don't have a redirect URL.
Best regards,
Fabian

**Comment by JMPerez** [comment]
@feedm3 Sure! Have a look at https://github.com/thelinmichael/spotify-web-api-node/blob/master/examples/access-token-using-client-credentials.js

**Comment by tetreault** [comment]
@JMPerez something really has to be up or there is some gap somewhere in some documentation... I tried this on an Ubuntu EC2 instance as well as locally. I even regenerated my Spotify ID & Secret. The above example you give yields the following: 

`Something went wrong when retrieving an access token Bad Request`

I dont get WTF the problem is (not that its your fault at all, I'm just running out of ideas...)

**Comment by tetreault** [comment]
Is there a max version of node this is compatible with? I'm running: 

Node: v7.7.1
NPM: v4.1.2

**Comment by tetreault** [comment]
I should clarify @JMPerez I can use the Node API perfectly when I pull a random artist's album. When I try to Auth so I can pull a public playlist for a given user though, this is where the trouble is.

**Comment by feedm3** [comment]
@JMPerez thank you, it works! :)

**Comment by JMPerez** [comment]
@tetreault closing this ticket since @feedm3 got it solved. Let's continue looking at the other 400 Bad Request.

**Comment by tetreault** [comment]
@JMPerez Is it easier if its moved over to [here - #321 on Spotify Web API](https://github.com/spotify/web-api/issues/321). There was an resolved thread about the same type of issue I'm facing. Thanks again for your willingness to help!!
