### ISSUE TITLE
Using the API for my web application

### ISSUE THREAD

**Issue by dennisfrijlink** [thelinmichael/spotify-web-api-node#258]
Dear Micheal,

I'm a Sonos and Spotify user and at the moment developing a sonos web controller. The only thing I struggle with is the search engine. I searched a lot and found your spotify-web-api. I read your documentation and I'm struggling with implementing your functions into my .js file. In other words, how do  I use your API?

thank you in advance

**Comment by kevinguebert** [comment]
Hey - I think more information would need to be provided instead of a "how do I use it" kind of question. What part specifically are you struggling with? If you can break out your question in to more specifics, it would be easier to answer.

There are also a bunch of tutorials out there to help get you started - here's on from September of this year: https://hackernoon.com/build-a-react-shuffle-blog-using-the-spotify-api-d5498d47c47b
