### ISSUE TITLE
Error 401 

### ISSUE THREAD

**Issue by chan-kh** [thelinmichael/spotify-web-api-node#311]
Hi, I am having a 401 error after I have save the access token. I was trying to follow some of those examples. The following is my code snippet. 
```
spotifyApi.clientCredentialsGrant()
  .then(function(data) {
    console.log('The access token expires in ' + data.body['expires_in']);
    console.log('The access token is ' + data.body['access_token']);

    // Save the access token so that it's used in future calls
    spotifyApi.setAccessToken(data.body['access_token']);
  }, function(err) {
    console.log('Something went wrong when retrieving an access token', err.message);
  });

spotifyApi.getArtistAlbums('43ZHCT0cAZBISjO8DG9PnE').then(
    function(data) {
      console.log('Artist albums', data.body);
    },
    function(err) {
      console.error(err);
    }
  );
```
My terminal output is 
```
[Error [WebapiError]: Unauthorized] { statusCode: 401 }
The access token expires in 3600
The access token is BQC5dKw5ArfFn7t-NgutgOOCRXoiWLvP6i9N0sUQj4RdaTsQYvZXN26kMU47EfS2jM4Lo1rwHdLLovo1aag
```

However, the code ran well if I move `.getArtist()` in `.clientCredentialsGrant()`
```
spotifyApi.clientCredentialsGrant()
  .then(function(data) {
    console.log('The access token expires in ' + data.body['expires_in']);
    console.log('The access token is ' + data.body['access_token']);

    // Save the access token so that it's used in future calls
    spotifyApi.setAccessToken(data.body['access_token']);
 
    spotifyApi.getArtist('2hazSY4Ef3aB9ATXW7F5w3')
    .then(function(data) {
      console.log('Artist information', data.body);
    }, function(err) {
      console.error(err);
    });
  
  }, function(err) {
    console.log('Something went wrong when retrieving an access token', err.message);
  });
```
Any help or suggestion will be appreciated.

**Comment by saadmas** [comment]
In your first code snippet, **getArtistAlbums** doesn't wait for **clientCredentialsGrant** to finish since **clientCredentialsGrant** is an async operation and **getArtistAlbums** is _not_ in the `then` block

In your second code snippet, **getArtistAlbums** runs after **clientCredentialsGrant** is completed, since it is inside the `then` block

This has to do with the way async operations work in JS  (promises, promise chaining etc). 

Btw, using [async/await](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await) will make your code easier to read and reason about (not _necessary_ though)

**Comment by chan-kh** [comment]
@saadmas Thank you very much. I did not know that is an async operation, it makes sense now.
