### ISSUE TITLE
Can we fetch all user (playlist, friendlist etc) data without a limit?

### ISSUE THREAD

**Issue by yulafezmesi** [thelinmichael/spotify-web-api-node#360]
Spotify API provide this count of data? I tried two endpoint which is getMyTopTracks and getMyTopArtists. This functions return maximum 50 record with time_range.

I want to compare two time intervals of all data and find the increase. Is that possible?

**Comment by thelinmichael** [comment]
> I want to compare two time intervals of all data and find the increase. Is that possible?

Sounds like the very reason the API provides the `time_range` parameter. Spotify has basically done the work for you so that you shouldn't need to make the comparison yourself. 

I don't think this issue fits very well in this project though since this is just a JS client. The best way forward is to bring this is up with the Spotify team. Please re-open if you disagree, otherwise just let it stay closed.
