### ISSUE TITLE
Is limit, offset working with getPlaylist() function?

### ISSUE THREAD

**Issue by mhlavacka** [thelinmichael/spotify-web-api-node#50]
I'm trying to get tracks from playlist that is longer than 100 tracks and there is a limit of a 100. I tried changing setting {limit : x, offset: x}, but it seems not working.

**Comment by JMPerez** [comment]
@mhlavacka Limit and offset are being passed as an object to the internal `request` object (see https://github.com/thelinmichael/spotify-web-api-node/blob/master/src/spotify-web-api.js#L791), so this should work. Could you provide an example of the call, or even better check what url is being requested?

**Comment by mhlavacka** [comment]
I'm doing exactly this, but it returns all tracks from 0 - 30, limit : 5 and offset 0.

I'm using [Meteor Spotify Web API](https://github.com/xinranxiao/meteor-spotify-web-api), Meteor wrapper for your api. Guess I should at first look there.

```javascript
getUserPlaylist: function(owner, playlist) {
    var spotifyApi = new SpotifyWebApi();
    var response = spotifyApi.getPlaylist('spotifydiscover', '0vL3R9wDeAwmXTTuRATa14', { limit : 5, offset : 10 });

    if (checkTokenRefreshed(response, spotifyApi)) {
      response = spotifyApi.getPlaylist('spotifydiscover', '0vL3R9wDeAwmXTTuRATa14', { limit : 5, offset : 10 });
    }

    return response.data.body
},
```

**Comment by JMPerez** [comment]
@mhlavacka I see that the meteor wrapper only deals with authentication and it doesn't change the implementation the `getPlaylist()` function.

I just realised the problem is that you want to use `.getPlaylistTracks()` to pass a limit and offset. [The request to get a playlist](https://developer.spotify.com/web-api/get-playlist/) doesn't accept `limit` nor `offset` and the options are limited to `fields` and `market`. There is no way to limit the amount of tracks you get in that request, and it will be 100 max. If you want to get the following chunk you can use the url provided in the `tracks.next` field.

**Comment by mhlavacka** [comment]
@JMPerez  Thanks for a quick explanation. That's exactly what I needed.

**Comment by SwapnilSoni1999** [comment]
> @mhlavacka I see that the meteor wrapper only deals with authentication and it doesn't change the implementation the `getPlaylist()` function.
> 
> I just realised the problem is that you want to use `.getPlaylistTracks()` to pass a limit and offset. `getPlaylist()` makes a request to [this endpoint](https://developer.spotify.com/web-api/get-playlist/) that doesn't accept `limit` nor `offset`, and the options are limited to `fields` and `market`. There is no way to limit the amount of tracks you get in that request, and it will be 100 max. If you want to get the following chunk you can use the url provided in the `tracks.next` field.

Can I please have an example for calling that next url, would be helpful. Thanks
