### ISSUE TITLE
Use something other than restler so module is browerify'able

### ISSUE THREAD

**Issue by SomeoneWeird** [thelinmichael/spotify-web-api-node#56]
Title says it all, what do you think? I can probably make this change.

**Comment by JMPerez** [comment]
@SomeoneWeird This would be amazing. I tried some time ago to make the wrapper client-side compatible using `node-fetch`, but in the end I didn't continue. But this would be really interesting, since it would allow us to merge this project and https://github.com/JMPerez/spotify-web-api-js. After all, they have almost the same API.

Please, feel free to propose a change if you have something in mind.
