### ISSUE TITLE
Is there a way to check expiration status of access token?

### ISSUE THREAD

**Issue by ajhaupt7** [thelinmichael/spotify-web-api-node#89]
After my access token expires I get an error saying 'Unauthorized.' This is expected since my token has expired, but is there a way to check on the expiration status of the token to see if we need to refresh it before the request is made? I was thinking I could calculate the expiration datetime when first receiving the token and check before each request to see if it's past that time, but wondering if this was built in already. Thanks!

**Comment by JMPerez** [comment]
@ajhaupt7 Short answer is that there is no direct way to check whether a token has expired, unless you try it and get `401 Unathorized`. What we usually do is the following:

1. When you obtain an `access_token` you also get an `expires_in` value with the amount of seconds during which the access token is valid. Persist both somewhere.
2. You can run a timer (eg `setTimeout`) to schedule a refresh in `expires_in` seconds. That way you make sure you always have a valid token without checking the expiration time every time you are making a request, although if you don't plan to make more than 1 request per hour it might be worthless keeping it up to date. Alternatively you can wrap your calls to the API in some code that will check for the expiration time, refresh if needed, and then execute your request.
3. When you make the request to the API you could still get `401 Unauthorized`. In some corner cases it might be that there is a batch invalidation of access tokens, or users revoke access to your application. Thus, you should always handle the 401 error and try to refresh the access token. If you get an access token you could rety the request, otherwise you would consider that the user is not logged in.

**Comment by ajhaupt7** [comment]
perfect, thanks @JMPerez
