### ISSUE TITLE
authorizationCodeGrant broken on 2.3.6, working on 2.3.1

### ISSUE THREAD

**Issue by antonioandrade** [thelinmichael/spotify-web-api-node#90]
While the the `access-token-using-client-credentials.js`example works fine at version 2.3.1, it won't run on 2.3.6 (400 Bad Request). 
I [suspect](https://github.com/thelinmichael/spotify-web-api-node/issues/72) this is related to superagent usage.
Cheers

**Comment by JMPerez** [comment]
@antonioandrade The error is caused by the credentials being invalid. Some examples contain a pair of client id / client secret that are not valid anymore. I have tried it out creating an application on [the developer site](https://developer.spotify.com/my-applications) and using those credentials and it works properly.
